on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      terraform-version:
        required: true
        type: string
      tflint-version:
        required: true
        type: string
      run-tflint:
        required: true
        type: boolean
      run-tftest:
        required: true
        type: boolean

defaults:
  run:
    shell: bash

jobs:

  tflint:
    name: Lint Terraform
    runs-on: ${{ inputs.runner }}
    if: inputs.run-tflint
    steps:
      - uses: actions/cache@v4
        name: Cache tflint plugins
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ inputs.runner }}-${{ hashFiles('.tflint.hcl') }}
          restore-keys: |
            tflint-${{ inputs.runner }}-

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: ${{ inputs.tflint-version }}

      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact

  tftest:
    name: Test Terraform
    runs-on: ${{ inputs.runner }}
    if: inputs.run-tftest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/terraform-init
        with:
          terraform-version: ${{ inputs.terraform-version }}

      - run: terraform test
